version: "3"
services:
  app:
    restart: always
    build: .
    command: "gunicorn -c gunicorn.conf.py BSproutMall.wsgi:application"
    volumes:
      - .:/code
    expose:
      - "8088"
    depends_on:
      - db
    networks:
      - web_network
      - db_network
  nginx:
    restart: always
    image: nginx:latest
    ports:
#      - "80:8088"
      - "443:443"
    volumes:
      - ./collected_static:/code/collected_static # 将静态文件放在nginx 服务器
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - web_network
  db:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - db_network
networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge
volumes:
  data-volume:

