# Generated by Django 4.2.3 on 2023-07-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpuInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('amount', models.FloatField(max_length=99999, verbose_name='商品金额')),
                ('main_url', models.CharField(max_length=10000, verbose_name='商品主图')),
                ('img_urls', models.CharField(max_length=10000, verbose_name='商品描述图')),
            ],
        ),
    ]
